/**
 * Builds site/img/icons.svg, an SVG sprite holding only the icons the site uses.
 *
 * Shipping a sprite instead of the full Font Awesome stylesheet saves roughly
 * 100 KB and a third-party request. Reference an icon in HTML with:
 *   <svg class="icon" aria-hidden="true"><use href="img/icons.svg#code"></use></svg>
 *
 * Usage: npm run icons
 */
import { readFile, writeFile } from 'node:fs/promises';
import { createRequire } from 'node:module';
import path from 'node:path';

const require = createRequire(import.meta.url);
const faRoot = path.dirname(require.resolve('@fortawesome/fontawesome-free/package.json'));

// [sprite id, Font Awesome style, Font Awesome icon name]
const ICONS = [
  ['arrow-right', 'solid', 'arrow-right'],
  ['external', 'solid', 'arrow-up-right-from-square'],
  ['bars', 'solid', 'bars'],
  ['basketball', 'solid', 'basketball'],
  ['book', 'solid', 'book-open'],
  ['calendar', 'solid', 'calendar-days'],
  ['code', 'solid', 'code'],
  ['download', 'solid', 'download'],
  ['drum', 'solid', 'drum'],
  ['envelope', 'solid', 'envelope'],
  ['fire', 'solid', 'fire'],
  ['gamepad', 'solid', 'gamepad'],
  ['github', 'brands', 'github'],
  ['heart-hand', 'solid', 'hand-holding-heart'],
  ['layers', 'solid', 'layer-group'],
  ['linkedin', 'brands', 'linkedin-in'],
  ['microchip', 'solid', 'microchip'],
  ['moon', 'solid', 'moon'],
  ['mountain', 'solid', 'mountain'],
  ['palette', 'solid', 'palette'],
  ['pepper', 'solid', 'pepper-hot'],
  ['people', 'solid', 'people-group'],
  ['plane', 'solid', 'plane-departure'],
  ['play', 'solid', 'play'],
  ['seedling', 'solid', 'seedling'],
  ['server', 'solid', 'server'],
  ['sparkles', 'solid', 'wand-magic-sparkles'],
  ['stop', 'solid', 'stop'],
  ['sun', 'solid', 'sun'],
  ['utensils', 'solid', 'utensils'],
  ['vr', 'solid', 'vr-cardboard'],
  ['xmark', 'solid', 'xmark'],
];

async function toSymbol([id, style, name]) {
  const svg = await readFile(path.join(faRoot, 'svgs', style, `${name}.svg`), 'utf8');
  const viewBox = svg.match(/viewBox="([^"]+)"/)?.[1];
  const paths = svg.match(/<path[^>]*\/>/g);
  if (!viewBox || !paths) throw new Error(`Could not parse ${style}/${name}.svg`);
  return `  <symbol id="${id}" viewBox="${viewBox}">${paths.join('')}</symbol>`;
}

const symbols = await Promise.all(ICONS.map(toSymbol));
const sprite = [
  '<svg xmlns="http://www.w3.org/2000/svg">',
  '  <!-- Font Awesome Free 6 by @fontawesome, https://fontawesome.com, CC BY 4.0. Generated by scripts/build-icons.js -->',
  ...symbols,
  '</svg>',
  '',
].join('\n');

await writeFile('site/img/icons.svg', sprite);
console.log(`Wrote site/img/icons.svg with ${symbols.length} icons`);
